apiVersion: v1
kind: Pod
metadata:
  name: pod
  labels:
    app: app
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
    envFrom:
    - configMapRef:
        name: app-config
    - secretRef:
        name: app-secret
